version: '3.8'

services:
  db:
    image: postgres:14
    container_name: apex-2-postgres
    env_file:
      - .env
    ports:
      - '5432-5432'
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data
