version: '3.8'

services:
  db:
    image: postgres:14
    container_name: apex-postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: apex-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "apex"
      RABBITMQ_DEFAULT_PASS: "apex"
    ports:
      - '5672:5672'     
      - '15672:15672'  
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq
